name: Docker Image CI

on: push

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag knxd:latest
    - name: Inspect Docker image
      run: docker image inspect knxd:latest  
    - name: Run knxd Container (no net host)
      run: |
        pwd
        docker run -p 3671:3671 -p 6720:6720 knxd:latest knxd -e 1.1.244 -E 1.1.246:8 -f9 --send-delay=30 -B single -b ipt:192.168.178.39 -c -DTRS
      timeout-minutes: 1
      continue-on-error: true
    - name: Run knxd Container (with net host)
      run: |
        pwd
        docker run --network host knxd:latest knxd -e 1.1.244 -E 1.1.246:8 -f9 --send-delay=30 -B single -b ipt:192.168.178.39 -c -DTRS
      timeout-minutes: 1
      continue-on-error: true
